# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.example
canonical: http://hl7.org/fhir/fr/example
name: ExampleIG
title: ANS IG Example
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
dependencies:
  hl7.fhir.fr.core:
    uri: 'https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0'
    version: 1.1.0
    id: frcore
  ans.cisis.fhir.r4:
    uri: 'https://simplifier.net/packages/ans.cisis.fhir.r4/2.1.0'
    version: 2.1.0
    id: anscis
  ANS.annuaire.fhir.r4:
    uri: 'https://simplifier.net/packages/ANS.annuaire.fhir.r4/0.2.0'
    version: 0.2.0
    id: ansAnnuaire
parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        st_flux1.md:
            title: Flux 01
        st_flux2.md:
            title: Flux 02
    # specifications_fonctionnelles.md:
    #     sf_ajout.md:
    #         title: Fonctionnalité 1
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Description des flux:
        Construction des flux: construction_des_flux.html
        Flux 01: st_flux1.html
        Flux 02: st_flux2.html
    # Spécifications fonctionnelles:
    #     Spécifications fonctionnelles: specifications_fonctionnelles.html
    #     Fonctionnalité 1: sf_ajout.html
    Ressources de conformance: artifacts.html
    Autres ressources:
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
